[package]
name = "yuml-rs"
version = "0.1.0"
authors = ["mibes <mibes@avaya.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.3.9"
derive_more = "0.99.11"
itertools = "0.9.0"