[package]
name = "yuml-cli"
version = "0.1.0"
authors = ["mibes <mibes@avaya.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="2"

# local
yuml-rs = { path = "../yuml-rs" }